<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:TalendMetadata="http://www.talend.org/metadata/connection/2010" xmlns:orgomg.cwm.resource.relational="http:///orgomg/cwm/resource/relational.ecore">
  <TalendMetadata:DatabaseConnection xmi:id="_8e1ikMWFEeqf57p5GJceZw" name="sql_server_talend" id="_enHZ0La8EeqMUrAkckOGvA" label="sql_server_talend" dataPackage="_8e1insWFEeqf57p5GJceZw" DatabaseType="Microsoft SQL Server" DriverClass="net.sourceforge.jtds.jdbc.Driver" URL="jdbc:jtds:sqlserver://10.1.51.25:1433/UPS_Dev;" dbVersionString="JTDS" Port="1433" Username="sa" Password="enc:system.encryption.key.v1:Bb31Nc5lP21h9sag83lM7Ydis5/TlobxoHimZ/XKweZol2TS" ServerName="10.1.51.25" DatasourceName="" FileFieldName="" SID="UPS_Dev" SqlSynthax="" StringQuote="" NullChar="" DbmsId="id_MSSQL" ProductId="SQL_SERVER" AdditionalParams="" StandardSQL="true" SQLMode="false" UiSchema="">
    <taggedValue xmi:id="_8e1ikcWFEeqf57p5GJceZw" tag="Is Conn Need Reload" value="true"/>
    <taggedValue xmi:id="_8e1iksWFEeqf57p5GJceZw" tag="package filter" value=""/>
    <taggedValue xmi:id="_8e1ik8WFEeqf57p5GJceZw" tag="Status" value=""/>
    <taggedValue xmi:id="_8e1ilMWFEeqf57p5GJceZw" tag="Version" value="0.1"/>
    <taggedValue xmi:id="_8e1ilcWFEeqf57p5GJceZw" tag="Purpose" value=""/>
    <taggedValue xmi:id="_8e1ilsWFEeqf57p5GJceZw" tag="Description" value=""/>
    <taggedValue xmi:id="_8e1il8WFEeqf57p5GJceZw" tag="Author" value=""/>
    <taggedValue xmi:id="_8e1imMWFEeqf57p5GJceZw" tag="otherParameter"/>
    <taggedValue xmi:id="_8e1imcWFEeqf57p5GJceZw" tag="DB ProductName" value="Microsoft SQL Server"/>
    <taggedValue xmi:id="_8e1imsWFEeqf57p5GJceZw" tag="DB ProductVersion" value="10.50.1600"/>
    <taggedValue xmi:id="_8e1im8WFEeqf57p5GJceZw" tag="DB IdentifierQuoteString" value="&quot;"/>
    <parameters xmi:id="_8e1inMWFEeqf57p5GJceZw" key="CONN_PARA_KEY_USERNAME" value="sa"/>
    <parameters xmi:id="_8e1incWFEeqf57p5GJceZw" key="CONN_PARA_KEY_MAPRDB_TABLE_NS_MAPPING" value=""/>
  </TalendMetadata:DatabaseConnection>
  <orgomg.cwm.resource.relational:Catalog xmi:id="_8e1insWFEeqf57p5GJceZw" name="UPS_Dev" dataManager="_8e1ikMWFEeqf57p5GJceZw">
    <ownedElement xsi:type="orgomg.cwm.resource.relational:Schema" xmi:id="_8e1in8WFEeqf57p5GJceZw" name="db_accessadmin"/>
    <ownedElement xsi:type="orgomg.cwm.resource.relational:Schema" xmi:id="_8e1ioMWFEeqf57p5GJceZw" name="db_backupoperator"/>
    <ownedElement xsi:type="orgomg.cwm.resource.relational:Schema" xmi:id="_8e1iocWFEeqf57p5GJceZw" name="db_datareader"/>
    <ownedElement xsi:type="orgomg.cwm.resource.relational:Schema" xmi:id="_8e1iosWFEeqf57p5GJceZw" name="db_datawriter"/>
    <ownedElement xsi:type="orgomg.cwm.resource.relational:Schema" xmi:id="_8e1io8WFEeqf57p5GJceZw" name="db_ddladmin"/>
    <ownedElement xsi:type="orgomg.cwm.resource.relational:Schema" xmi:id="_8e1ipMWFEeqf57p5GJceZw" name="db_denydatareader"/>
    <ownedElement xsi:type="orgomg.cwm.resource.relational:Schema" xmi:id="_8e1ipcWFEeqf57p5GJceZw" name="db_denydatawriter"/>
    <ownedElement xsi:type="orgomg.cwm.resource.relational:Schema" xmi:id="_8e1ipsWFEeqf57p5GJceZw" name="db_owner"/>
    <ownedElement xsi:type="orgomg.cwm.resource.relational:Schema" xmi:id="_8e1ip8WFEeqf57p5GJceZw" name="db_securityadmin"/>
    <ownedElement xsi:type="orgomg.cwm.resource.relational:Schema" xmi:id="_8e1iqMWFEeqf57p5GJceZw" name="dbo"/>
    <ownedElement xsi:type="orgomg.cwm.resource.relational:Schema" xmi:id="_8e1iqcWFEeqf57p5GJceZw" name="guest"/>
    <ownedElement xsi:type="orgomg.cwm.resource.relational:Schema" xmi:id="_8e1iqsWFEeqf57p5GJceZw" name="INFORMATION_SCHEMA"/>
    <ownedElement xsi:type="orgomg.cwm.resource.relational:Schema" xmi:id="_8e1iq8WFEeqf57p5GJceZw" name="sys"/>
  </orgomg.cwm.resource.relational:Catalog>
</xmi:XMI>
