<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:TalendMetadata="http://www.talend.org/metadata/connection/2010" xmlns:orgomg.cwm.resource.relational="http:///orgomg/cwm/resource/relational.ecore">
  <TalendMetadata:DatabaseConnection xmi:id="_xYVvQMWFEeqf57p5GJceZw" name="sql_server_talend" id="_enHZ0La8EeqMUrAkckOGvA" label="sql_server_talend" dataPackage="_xYVvTsWFEeqf57p5GJceZw" DatabaseType="Microsoft SQL Server" DriverClass="net.sourceforge.jtds.jdbc.Driver" URL="jdbc:jtds:sqlserver://10.1.51.25:1433/BullsEye;" dbVersionString="JTDS" Port="1433" Username="sa" Password="enc:system.encryption.key.v1:DsS7/TrlfIi/9Fcp/rV9Z+itWUVoKDQ4m6dB+poPX53I6X0w" ServerName="10.1.51.25" DatasourceName="" FileFieldName="" SID="BullsEye" SqlSynthax="" StringQuote="" NullChar="" DbmsId="id_MSSQL" ProductId="SQL_SERVER" AdditionalParams="" StandardSQL="true" SQLMode="false" UiSchema="">
    <taggedValue xmi:id="_xYVvQcWFEeqf57p5GJceZw" tag="Is Conn Need Reload" value="true"/>
    <taggedValue xmi:id="_xYVvQsWFEeqf57p5GJceZw" tag="package filter" value=""/>
    <taggedValue xmi:id="_xYVvQ8WFEeqf57p5GJceZw" tag="Status" value=""/>
    <taggedValue xmi:id="_xYVvRMWFEeqf57p5GJceZw" tag="Version" value="0.1"/>
    <taggedValue xmi:id="_xYVvRcWFEeqf57p5GJceZw" tag="Purpose" value=""/>
    <taggedValue xmi:id="_xYVvRsWFEeqf57p5GJceZw" tag="Description" value=""/>
    <taggedValue xmi:id="_xYVvR8WFEeqf57p5GJceZw" tag="Author" value=""/>
    <taggedValue xmi:id="_xYVvSMWFEeqf57p5GJceZw" tag="otherParameter"/>
    <taggedValue xmi:id="_xYVvScWFEeqf57p5GJceZw" tag="DB ProductName" value="Microsoft SQL Server"/>
    <taggedValue xmi:id="_xYVvSsWFEeqf57p5GJceZw" tag="DB ProductVersion" value="10.50.1600"/>
    <taggedValue xmi:id="_xYVvS8WFEeqf57p5GJceZw" tag="DB IdentifierQuoteString" value="&quot;"/>
    <parameters xmi:id="_xYVvTMWFEeqf57p5GJceZw" key="CONN_PARA_KEY_USERNAME" value="sa"/>
    <parameters xmi:id="_xYVvTcWFEeqf57p5GJceZw" key="CONN_PARA_KEY_MAPRDB_TABLE_NS_MAPPING" value=""/>
  </TalendMetadata:DatabaseConnection>
  <orgomg.cwm.resource.relational:Catalog xmi:id="_xYVvTsWFEeqf57p5GJceZw" name="BullsEye" dataManager="_xYVvQMWFEeqf57p5GJceZw">
    <ownedElement xsi:type="orgomg.cwm.resource.relational:Schema" xmi:id="_xYVvT8WFEeqf57p5GJceZw" name="db_accessadmin"/>
    <ownedElement xsi:type="orgomg.cwm.resource.relational:Schema" xmi:id="_xYVvUMWFEeqf57p5GJceZw" name="db_backupoperator"/>
    <ownedElement xsi:type="orgomg.cwm.resource.relational:Schema" xmi:id="_xYVvUcWFEeqf57p5GJceZw" name="db_datareader"/>
    <ownedElement xsi:type="orgomg.cwm.resource.relational:Schema" xmi:id="_xYVvUsWFEeqf57p5GJceZw" name="db_datawriter"/>
    <ownedElement xsi:type="orgomg.cwm.resource.relational:Schema" xmi:id="_xYVvU8WFEeqf57p5GJceZw" name="db_ddladmin"/>
    <ownedElement xsi:type="orgomg.cwm.resource.relational:Schema" xmi:id="_xYVvVMWFEeqf57p5GJceZw" name="db_denydatareader"/>
    <ownedElement xsi:type="orgomg.cwm.resource.relational:Schema" xmi:id="_xYVvVcWFEeqf57p5GJceZw" name="db_denydatawriter"/>
    <ownedElement xsi:type="orgomg.cwm.resource.relational:Schema" xmi:id="_xYVvVsWFEeqf57p5GJceZw" name="db_owner"/>
    <ownedElement xsi:type="orgomg.cwm.resource.relational:Schema" xmi:id="_xYVvV8WFEeqf57p5GJceZw" name="db_securityadmin"/>
    <ownedElement xsi:type="orgomg.cwm.resource.relational:Schema" xmi:id="_xYVvWMWFEeqf57p5GJceZw" name="dbo"/>
    <ownedElement xsi:type="orgomg.cwm.resource.relational:Schema" xmi:id="_xYVvWcWFEeqf57p5GJceZw" name="guest"/>
    <ownedElement xsi:type="orgomg.cwm.resource.relational:Schema" xmi:id="_xYVvWsWFEeqf57p5GJceZw" name="INFORMATION_SCHEMA"/>
    <ownedElement xsi:type="orgomg.cwm.resource.relational:Schema" xmi:id="_xYVvW8WFEeqf57p5GJceZw" name="sys"/>
  </orgomg.cwm.resource.relational:Catalog>
</xmi:XMI>
