<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:TalendMetadata="http://www.talend.org/metadata/connection/2010" xmlns:orgomg.cwm.resource.relational="http:///orgomg/cwm/resource/relational.ecore">
  <TalendMetadata:DatabaseConnection xmi:id="_aiIKgMWbEeqf57p5GJceZw" name="sql_server_talend" id="_enHZ0La8EeqMUrAkckOGvA" label="sql_server_talend" dataPackage="_aiIKjsWbEeqf57p5GJceZw" DatabaseType="Microsoft SQL Server" DriverClass="net.sourceforge.jtds.jdbc.Driver" URL="jdbc:jtds:sqlserver://10.1.51.25:1433/Talend;" dbVersionString="JTDS" Port="1433" Username="sa" Password="enc:system.encryption.key.v1:X/MAPyhVUBP4CKf4qdl/wCakA9rsAlNhpPAaWnxPAEBaYPsE" ServerName="10.1.51.25" DatasourceName="" FileFieldName="" SID="Talend" SqlSynthax="" StringQuote="" NullChar="" DbmsId="id_MSSQL" ProductId="SQL_SERVER" AdditionalParams="" StandardSQL="true" SQLMode="false" UiSchema="">
    <taggedValue xmi:id="_aiIKgcWbEeqf57p5GJceZw" tag="Is Conn Need Reload" value="true"/>
    <taggedValue xmi:id="_aiIKgsWbEeqf57p5GJceZw" tag="package filter" value=""/>
    <taggedValue xmi:id="_aiIKg8WbEeqf57p5GJceZw" tag="Status" value=""/>
    <taggedValue xmi:id="_aiIKhMWbEeqf57p5GJceZw" tag="Version" value="0.1"/>
    <taggedValue xmi:id="_aiIKhcWbEeqf57p5GJceZw" tag="Purpose" value=""/>
    <taggedValue xmi:id="_aiIKhsWbEeqf57p5GJceZw" tag="Description" value=""/>
    <taggedValue xmi:id="_aiIKh8WbEeqf57p5GJceZw" tag="Author" value=""/>
    <taggedValue xmi:id="_aiIKiMWbEeqf57p5GJceZw" tag="otherParameter"/>
    <taggedValue xmi:id="_aiIKicWbEeqf57p5GJceZw" tag="DB ProductName" value="Microsoft SQL Server"/>
    <taggedValue xmi:id="_aiIKisWbEeqf57p5GJceZw" tag="DB ProductVersion" value="10.50.1600"/>
    <taggedValue xmi:id="_aiIKi8WbEeqf57p5GJceZw" tag="DB IdentifierQuoteString" value="&quot;"/>
    <parameters xmi:id="_aiIKjMWbEeqf57p5GJceZw" key="CONN_PARA_KEY_USERNAME" value="sa"/>
    <parameters xmi:id="_aiIKjcWbEeqf57p5GJceZw" key="CONN_PARA_KEY_MAPRDB_TABLE_NS_MAPPING" value=""/>
  </TalendMetadata:DatabaseConnection>
  <orgomg.cwm.resource.relational:Catalog xmi:id="_aiIKjsWbEeqf57p5GJceZw" name="Talend" dataManager="_aiIKgMWbEeqf57p5GJceZw">
    <ownedElement xsi:type="orgomg.cwm.resource.relational:Schema" xmi:id="_aiIKj8WbEeqf57p5GJceZw" name="db_accessadmin"/>
    <ownedElement xsi:type="orgomg.cwm.resource.relational:Schema" xmi:id="_aiIKkMWbEeqf57p5GJceZw" name="db_backupoperator"/>
    <ownedElement xsi:type="orgomg.cwm.resource.relational:Schema" xmi:id="_aiIKkcWbEeqf57p5GJceZw" name="db_datareader"/>
    <ownedElement xsi:type="orgomg.cwm.resource.relational:Schema" xmi:id="_aiIKksWbEeqf57p5GJceZw" name="db_datawriter"/>
    <ownedElement xsi:type="orgomg.cwm.resource.relational:Schema" xmi:id="_aiIKk8WbEeqf57p5GJceZw" name="db_ddladmin"/>
    <ownedElement xsi:type="orgomg.cwm.resource.relational:Schema" xmi:id="_aiIKlMWbEeqf57p5GJceZw" name="db_denydatareader"/>
    <ownedElement xsi:type="orgomg.cwm.resource.relational:Schema" xmi:id="_aiIKlcWbEeqf57p5GJceZw" name="db_denydatawriter"/>
    <ownedElement xsi:type="orgomg.cwm.resource.relational:Schema" xmi:id="_aiIKlsWbEeqf57p5GJceZw" name="db_owner"/>
    <ownedElement xsi:type="orgomg.cwm.resource.relational:Schema" xmi:id="_aiIKl8WbEeqf57p5GJceZw" name="db_securityadmin"/>
    <ownedElement xsi:type="orgomg.cwm.resource.relational:Schema" xmi:id="_aiIKmMWbEeqf57p5GJceZw" name="dbo"/>
    <ownedElement xsi:type="orgomg.cwm.resource.relational:Schema" xmi:id="_aiIKmcWbEeqf57p5GJceZw" name="guest"/>
    <ownedElement xsi:type="orgomg.cwm.resource.relational:Schema" xmi:id="_aiIKmsWbEeqf57p5GJceZw" name="INFORMATION_SCHEMA"/>
    <ownedElement xsi:type="orgomg.cwm.resource.relational:Schema" xmi:id="_aiIKm8WbEeqf57p5GJceZw" name="sys"/>
  </orgomg.cwm.resource.relational:Catalog>
</xmi:XMI>
